### ISSUE TITLE
Example of usage "createContext" and "useContext"

### ISSUE THREAD

**Issue by sdcdsvsdv423** [ryansolid/mobx-jsx#10]
Please can you provide simple example how to use context functions?

**Comment by ryansolid** [comment]
Sure. Looking into this it looks like this library still uses an older version of my context code. I am working on a release for the underlying renderer so when I make the updates here, I will update this as well.

**Comment by ryansolid** [comment]
Ok updated including adding lazy to the library. Here is context example: https://codesandbox.io/s/mobx-counter-context-wlu1x

**Comment by sdcdsvsdv423** [comment]
The ability to change the state of child components is what caused the difficulty. The approach to change state by using `useContext` looks elegant. Thank you!

**Comment by sdcdsvsdv423** [comment]
Please can you publish release?

**Comment by ryansolid** [comment]
It should be already. It is v0.8.1. Make sure to update Babel Plugin JSX DOM Expressions as well.
