### ISSUE TITLE
Props for class components

### ISSUE THREAD

**Issue by Epskampie** [ryansolid/mobx-jsx#14]
Hey, I'm very interested in this approach, have been using mobx for a while, and was thinking if I need React at all.

I've been looking at your demos, but I can't figure out how to use props when using classes. `this.props` doesn't work. No arguments are passed to `render` as far as I can see.

Are props for classes supported at this point?

**Comment by ryansolid** [comment]
Thanks for pointing it out. Such a dumb oversight on my part and I never caught it since I never use class components. I will support both forms (just remember to call `super(props)`. I will let you know when this is released.

**Comment by ryansolid** [comment]
Should be released in v0.8.3.

**Comment by Epskampie** [comment]
Awesome! I’ll check it out tomorrow.
