### ISSUE TITLE
Browsers compatibility

### ISSUE THREAD

**Issue by 0x241F31** [ryansolid/mobx-jsx#18]
Hey, great project!
Does mobx-jsx support ie11 out of the box?
Thanks in advance.

**Comment by ryansolid** [comment]
No. Admittedly most of my work was associated with SolidJS and proxies as a baseline. I know the libraries (MobX, Solid) can be used without proxies but it figured by the time this became a decision point IE would be effectively dead.

At minimum you would need Babel to compile back to ES5. Polyfills for Promises, Symbols, and globalThis and probably polyfills around async/await and some Array methods. Polyfills associated with Babel might be sufficient.

I think that's about it. IE stopped receiving feature updates in 2014, but feature set is closer to ~2012. So the list is quite extensive.
