### ISSUE TITLE
Children not updating from updated props

### ISSUE THREAD

**Issue by boredofnames** [ryansolid/mobx-jsx#24]
Was playing around a bit with this, cool work. 
I noticed when passing an observable state as a prop to children components, then updating the state, the children won't update. 

You can see in this demo, changing the state manually will update the Level component, but changing it with setInterval doesn't.
https://codesandbox.io/s/mobx-counterfunctions-ojyzt?file=/index.js

**Comment by ryansolid** [comment]
One restriction of this approach is you can't prematurely destructure. This includes prop rest parameters in component definitions. Reactivity works based on property access so you can only do that within tracking contexts like computeds or in JSX bindings. To hoist expressions it's easiest to wrap in a function(thunk). Does that make sense. There are more details here but hopefully that's good to get started.

**Comment by boredofnames** [comment]
I see, makes sense. Thanks for the fast reply.

**Comment by ryansolid** [comment]
I was out earlier when I responded. I would have prefered to have a concrete example. If you change your level component to this it will work:

```jsx
function Level(props) {
  return (
    <div
      style={{
        margin: "3px",
        height: "20px",
        width: "100px",
        border:
          (100 / props.max) * props.value < props.min || (100 / props.max) * props.value > props.max
            ? "2px solid red"
            : "2px solid black"
      }}
    >
      <div
        style={{
          height: "20px",
          width: `${(100 / props.max) * props.value}px`,
          "background-color": props.color
        }}
      />
    </div>
  );
}
```
