### ISSUE TITLE
Avoid re-rendering complete list on push/modification?

### ISSUE THREAD

**Issue by titoBouzout** [ryansolid/mobx-jsx#25]
Im using something similar to the following. In theory if I push something I would like to render what I just pushed, not the complete list. I understand why this happens but cant see how to avoid it. Any ideas? Thanks! 

```jsx

class Root extends Component {
	@observable items = [1, 2, 3, 4, 5, 6, 7, 8]
	constructor() {
		setInterval(this.push, 2000)
	}
	push() {
		this.items.push(this.items.length + 1)
	}

	render() {
		return (
			<div>
				{this.items.map(
					function(item) {
						return <div>{item}</div>
					}
				)}
			</div>
		)
	}
}
```

**Comment by titoBouzout** [comment]
Alright, I have found the answer, you can do:

```jsx
import {  map } from 'mobx-jsx'
map(observableArray, fn(item){ })
```

instead of 

```jsx
observableArray.map(fn(item){ })
```


Is there any documentation with the complete list of available functions/utilities? Thanks!

**Comment by ryansolid** [comment]
I guess I'm not clear here. You can't use a normal map operator as that does the work ahead of time. The package exports a special helper that handles the proper memoization.
```jsx
import { map } from "mobx-jsx";

const list = observable(["Alpha", "Beta", "Gamma"]);

<ul>{
  map(list, item => <li>{item}</li>)
}</ul>
```

**Comment by ryansolid** [comment]
Not really. I guess I should document `lazy` and the Context API as well. Most of this stuff is backports of the work I've done with Solid so sometimes I forget to add docs for the particular library.

**Comment by titoBouzout** [comment]
Alright Ryan thanks a lot ♥

**Comment by titoBouzout** [comment]
Oh this is already documented on the readme, I must have forgotten and for some reason blinded. I have been looking for it everywhere for a straight hour till I learned about it on https://github.com/ryansolid/mobx-jsx/issues/4#issuecomment-513588233

**Comment by ryansolid** [comment]
I mean I'm not going to pretend my documentation is good. I write like a sentence or 2 and it isn't structured. I have a couple examples and none for that. I should make a simple Todo example for the library.
