### ISSUE TITLE
Effect is incorrectly disposed

### ISSUE THREAD

**Issue by Exelord** [ryansolid/mobx-jsx#29]
Hey Ryan :) I fell in love with the idea of compiled dom instructions. As I come from the Ember world, where Glimmer follows that path as well I wanted to give it a try and meet how it works from the kitchen.

I started my own project called [VZN (vision)](https://github.com/Exelord/vzn) which tries to be exactly what you try to build here :) I literally "stole" 😅  your code, refactored it, fixed a lot of issues, and apply the architecture similar to solid (I take it as  a great example :)) 

When I was doing so I noticed that the `effect` hook is not working correctly. It dispose the autorun when it shouldn't. The issue can be noticed right here https://codesandbox.io/s/mobx-counterfunctions-forked-b4y20?file=/index.js just click on the toggle few times :) For comparison see the version from VZN https://codesandbox.io/s/vzn-function-nxf33?file=/index.js

The issue was that on cleanup hook has been called after the autorun which had a side effect where it was used on the owner from the effect hook instead of the parent.

The fix was quite easy but took my like 5h to find out (though, I learned a lot! :D) 
https://github.com/Exelord/vzn/blob/master/packages/vzn/src/reactive/core.ts#L17

If you wish, I can create a PR with a fix :) At least that I can do for the inspiration ;) 

All the best!
Maciej

**Comment by ryansolid** [comment]
>  I literally "stole" 😅 your code, refactored it ....

Not the first time someone has done this and won't be the last (see Sinuous, Fidan). I think there is something really interesting here and lot of space to explore. 

Hmm.. interesting I have to admit this whole possible given that I had a glaring hole in the cleanup logic a couple releases ago where I was never disposing. Now I'm overdisposing. Pretty serious bug. I will probably have to fix this up ASAP as all my wrapper libraries(non-Solid) probably have it. So while I'd appreciate the PR to save me some time. About 12 hours from now I will likely be working on this anyway so I don't want to duplicate effort nor put you on a clock. So thank you very much for bringing this to my attention.

**Comment by ryansolid** [comment]
Whew.. this is just a MobX specific issue. They change the order of execution of nested computations where other libraries do not. In most libraries the time the running outer context and the parent context are the same. Thanks again for bringing this to my attention. Who knows how long it would have taken for me to notice.

**Comment by ryansolid** [comment]
Ok fixed in v0.12.1. Thanks so much.

**Comment by Exelord** [comment]
Awesome Thank you for all the work, Ryan!
