### ISSUE TITLE
[BUG] Context providers double side effects

### ISSUE THREAD

**Issue by Exelord** [ryansolid/mobx-jsx#30]
Hey Ryan, its me again ;)
While I still explore your code and play with the dom-expressions I noticed 1-2 bugs related to context and effects.

https://codesandbox.io/s/mobx-counter-context-bug-cqp1u

In the sandbox you can notice that besides The Clock component is called only once it has been somehow executed twice, as the timeout is doubling the counter.

~~The second one (maybe connected) is when you click on the Toggle button. You won't be able to show the component again. It may be still related to effect cleanup.~~

I was trying to debug it, but after 4h I land with no other clue :/ My bet is we are missing some `untracked fn` as autorun is firing too many times.

**Comment by ryansolid** [comment]
Yeah the second bug is related to the other issue if you update to 12.1 it goes away. But yeah the doubling is interesting. It's like there are 2 copies of the component, one attached and one not. When you toggle it (after you update) they can get out of sync with each other but clearly there is a ghost. The way it staggers makes me think there are multiple setInterval calls going on. My guess is my resolve children function is broken here. Probably another resolution timing based thing specific to MobX. I will investigate tonight.

**Comment by Exelord** [comment]
You are right. Sorry forgot to update. 

Indeed, its like ghost component. Actually I took this trace with `resolveChildren` already and its a dead end. If you remove it and just return children it works the same. What I noticed though, is that the Provider (createProvider) is called twice. I suspect it should be run only once 🤔

**Comment by Exelord** [comment]
I found the cause :) Its the Fragment. When you change it to eg `div` in the sandbox it works fine. Maybe its not aware of mobx reactivity and refresh with every change? 

Actually It looks like its sth with the memo.

**Comment by ryansolid** [comment]
Yeah I see it.. instead of using a computed I was just reusing effect to simulate it but it means that I'm running it once more on initialization. Yeah that won't fly. Ok need to find a different way to do memo in these wrapper libraries. This definitely affects all my non-Solid libraries then. It might be safe to just not initialize since we know the effect will run the first time anyway. Hmm..

**Comment by Exelord** [comment]
~~What if we just use `value.get();` instead of calling `fn()` inside of the memo effect? Then it will be executed without triggering autorun as the value contains untracked fn.
I might understand that wrong though. Still learning...~~

Ok I see the problem now

**Comment by ryansolid** [comment]
Looks to be fixed in v0.12.2. Thanks again.

**Comment by Exelord** [comment]
Works like a charm! Thank you! <3
