### ISSUE TITLE
mobx version 6 vs 5

### ISSUE THREAD

**Issue by titoBouzout** [ryansolid/mobx-jsx#42]
Hello! From time to time I want to install mobx-jsx but I run into the problem that installs mobx 6 and if I remember correctly it only works with mobx 5. I'm not completely sure, but the version seems to mismatch.

**Comment by ryansolid** [comment]
No. I am not aware of an issue with MobX 6. I've been using v6 in JS Frameworks Benchmark almost since release. Maybe I made the range to restrictive to only work with 6? But it should be fine. If there is a bug let me know.

**Comment by titoBouzout** [comment]
Thanks for your time. I figured something was messed up, deleting and reinstalling worked!
