### ISSUE TITLE
Any project example?

### ISSUE THREAD

**Issue by PierBover** [ryansolid/mobx-jsx#6]
I've been looking at this but somehow I can't make it work:

https://github.com/krausest/js-framework-benchmark/blob/master/frameworks/keyed/mobx-jsx/src/main.jsx

Here's what I have:

https://github.com/PierBover/mobx-jsx-webpack

It builds and renders, but when updating state it does not re-render.

**Comment by ryansolid** [comment]
Sure, I've done most of the example work for [Solid](https://github.com/ryansolid/solid) which is the same underlying renderer. I haven't spent much time on MobX specific examples.

I've created the counter example [MobX Counter](https://codesandbox.io/s/mobx-counter-uz7g9).

The part missing in your demo is that dynamic expressions need inner parens inside the braces `{( )}`. This indicates to the compiler to wrap the statement in an autorun. The compiler doesn't automatically wrap every expression to keep things slim.

**Comment by PierBover** [comment]
Awesome! Thanks for the help.

Would be great if you posted more examples in the Readme.
