### ISSUE TITLE
Does library support code splitting?

### ISSUE THREAD

**Issue by sdcdsvsdv423** [ryansolid/mobx-jsx#8]
Please can you provide an example or give some advise how to implement it.

**Comment by ryansolid** [comment]
Technically it is doable. Most bundlers will be looking for dynamic imports. That being said I have no specific helpers baked in. Solid my other library based on the same tech has the ability to lazy load Components built in.  Based on that a simple implementation might look like:

```jsx
import { observable, computed, untracked } from "mobx";

function lazy(fn) {
  return (props) => {
    let Comp;
    const result = observable.box()
    fn().then(({ default }) => result.set(default));
    const rendered = computed(() => (Comp = result.get()) && untracked(() => Comp(props)));
    return () => rendered.get();
  }
}

// then you'd use like:

// near top of file where you wish to lazy load
const SomeComponent = lazy(() => import("./SomeComponent"));

// inside your Component JSX
return (
    <>
      <SomeComponent someProp={state.data} />
    </>
  );
}
```
What this does is allow you to write a asynchronously loaded Component as though it is already there and then seamlessly work once it loads. You can picture only rendering this based on a conditional like a route and only loading the Component at that time. But just wrapping Components this way will allow code splitting regardless.

Admittedly it is pretty reasonable for the library to ship with such a method. I just haven't gotten around to implementing more advanced features in this library as it is more of a technology demonstration at this point. And as I generalize approaches taken with Solid I will back port here.

**Comment by sdcdsvsdv423** [comment]
Seems, this code is not working. Please can you look at [example](https://codesandbox.io/s/mobx-counterfunctions-zsbkf?fontsize=14)?

**Comment by ryansolid** [comment]
Yeah there were a couple issues. The .babelrc was incorrectly formatted, and you need to put the JSX code inside Components that your render.

I modified the example https://codesandbox.io/s/lazy-demo-mobx-ev95s

**Comment by sdcdsvsdv423** [comment]
Thank you!
